### ISSUE TITLE
"Failed to resolve dependency" when generating wrappers for components with relative imports

### ISSUE THREAD

**Issue by wyrmisis** [break-stuff/cem-plugin-react-wrapper#3]
When I run `npx cem analyze`, I get the following console output:

```sh
$ npx cem analyze --litelement
Failed to resolve dependency './Component'
[... same as above, as many times as relatively imported components are used]
[react-wrapper] - Generating React Wrappers
[react-wrapper] - Successfully Generated React Wrappers
```

Am I doing something wrong? I saw that the demo package does not contain components that use other components.

FWIW my file structure looks something like this:

```
- package
  | - dist
    | - components.js
  | - react
    | - NamespaceInput.js
    | - NamespaceInput.d.ts
  | - src
    | - components
      | - Input.ts
```

... where my components are generally like this:

```ts
// package/src/components/Component.ts

import './AnotherComponent';

export default class NamespaceComponent extends LitElement implements ComponentInterface {
  render() {
    return html`<namespace-another-component></namespace-another-component>`;
  }
}
```

**Comment by break-stuff** [comment]
They should be able to handle components that use other components without an issue. How are you mapping the module path?

**Comment by wyrmisis** [comment]
Sorry about taking a minute to get back to you, @break-stuff !

I don't have the module path mapped; I'm using the default setting.

**Comment by break-stuff** [comment]
Ah, ok. You will need to add a mapping to where your component's final output.

**Comment by break-stuff** [comment]
@wyrmisis, I was able to get out a patch release for you. Thanks for letting me know! Let me know if you run into any other issues.
